apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dave-data-pvc
  namespace: dave
  labels:
    app: dave
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard